spring:
  application:
    name: hystrix-consumer
server:
  port: 9020
name: lcw
password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${name}:${password}@localhost:8080/eureka/